apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: ${SERVICE_CERT_NAME}
  name: ${OBJECT_NAME}
  namespace: ${OBJECT_NAMESPACE}
  labels:
    app: ${APP_LABEL}
spec:
  type: ClusterIP
  ports:
  - name: metrics
    port: 8383
    protocol: TCP
    targetPort: metrics
  selector:
    app: ${APP_LABEL}
