# permissions for end users to edit localvolumes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: localvolume-editor-role
rules:
- apiGroups:
  - local.storage.openshift.io
  resources:
  - localvolumes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - local.storage.openshift.io
  resources:
  - localvolumes/status
  verbs:
  - get
