# permissions for end users to edit localvolumesets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: localvolumeset-editor-role
rules:
- apiGroups:
  - local.storage.openshift.io
  resources:
  - localvolumesets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - local.storage.openshift.io
  resources:
  - localvolumesets/status
  verbs:
  - get
