# permissions for end users to view localvolumediscoveryresults.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: localvolumediscoveryresult-viewer-role
rules:
- apiGroups:
  - local.storage.openshift.io
  resources:
  - localvolumediscoveryresults
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - local.storage.openshift.io
  resources:
  - localvolumediscoveryresults/status
  verbs:
  - get
