# permissions for end users to edit localvolumediscoveryresults.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: localvolumediscoveryresult-editor-role
rules:
- apiGroups:
  - local.storage.openshift.io
  resources:
  - localvolumediscoveryresults
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - local.storage.openshift.io
  resources:
  - localvolumediscoveryresults/status
  verbs:
  - get
