# permissions for end users to edit localvolumediscoveries.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: localvolumediscovery-editor-role
rules:
- apiGroups:
  - local.storage.openshift.io
  resources:
  - localvolumediscoveries
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - local.storage.openshift.io
  resources:
  - localvolumediscoveries/status
  verbs:
  - get
